# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  skindeepmag.com:
    nginx_wordpress_site_conf: nginx-includes/skindeepmag.com.conf.child.j2
    site_hosts:
      - canonical: skindeepmag.test
        redirects:
          - www.skindeepmag.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@example.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
          acf_pro_key: "{{ vault_acf_pro_key }}"
